version: "3.9"
services:
    db:
        image: mysql:8.0.19
        command: '--default-authentication-plugin=mysql_native_password'
        restart: always
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
            interval: 3s
            retries: 5
            start_period: 30s
        secrets:
            - db-password
        volumes:
            - db-data:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=ab_project
            - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
        expose:
            - 3306
            - 33060
    app:
        build: ./app
        image: pds-app:latest
        depends_on:
            db:
                condition: service_healthy

volumes:
    db-data:
secrets:
    db-password:
        file: designs/db_password.txt
